[project]
name = "sewadal-attendance-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "passlib[bcrypt]>=1.7.4",
    "bcrypt<5",
    "pymysql>=1.2.0",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.3",
]
